// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT
//! The zilc compile pipeline.
//!
//!   .zig  --zig build-obj--> LLVM IR --rewrite--> Fil-C dialect IR --+
//!                                                                    |--filc clang--> safe binary
//!   .c/.cpp/.o/.a -----------------------------------------------------+
//!
//! Nothing here patches Zig or LLVM: stock Zig emits the IR, `ir.zig` rewrites
//! two lines of it, and Fil-C's clang runs the GIMSO pass and links.
//! Background and limits: cmem/roadmap.md P2, cmem/known-issues.md KI-4…KI-6.

const std = @import("std");
// Through the module, not the file: importing "ir.zig" directly would put the
// same file in two modules, which Zig rejects.
const ir = @import("zilc").ir;
const ir_std = @import("zilc").stdpatch;

/// Who provides `main`.
///
/// Zig's own start code cannot run under Fil-C: it does
/// `@ptrFromInt(getauxval(AT_PHDR))` to find the program headers, and a pointer
/// forged from an integer carries no capability, so the first read of it traps
/// (KI-5). `.zig` therefore generates a C-ABI `main` that calls the user's
/// `main` directly, and Zig's `start.zig` never enters the build.
pub const Entry = enum { auto, c, zig };

/// Which runtime the program links.
///
///  * `.filc` — Fil-C's `libpizlo`, the runtime every gate run uses today.
///  * `.zig`  — zilc's own Zig runtime (P3), linked ahead of `libpizlo` so each
///    entry point it defines overrides Fil-C's and the rest fall through.
///    ⚠️ Reserved: it is refused until the runtime is ready for testing, so a
///    build can never claim the Zig runtime while silently linking Fil-C's.
pub const Runtime = enum { filc, zig };

pub const Options = struct {
    inputs: []const []const u8,
    output: []const u8,
    entry: Entry = .auto,
    /// Zig optimize mode. ⚠️ Debug needs zilc's patched Fil-C clang (KI-4).
    optimize: []const u8 = "ReleaseSafe",
    /// ⚠️ Fil-C's libc is musl; a gnu target fails to link on `*64` symbols (KI-6).
    target: []const u8 = "x86_64-linux-musl",
    /// Emit a linked executable, or stop at objects.
    emit: enum { exe, obj } = .exe,
    runtime: Runtime = .filc,
    zig: []const u8,
    filc: []const u8,
    keep_temps: bool = false,
    verbose: bool = false,
    /// Parallel parts for a big module's code generation: 0 = automatic (cores, at most
    /// `max_auto_jobs`), 1 = never split. See `filcCompile`.
    jobs: u32 = 0,
};

pub const Error = error{ ToolFailed, NoInputs, UnsupportedInput, RuntimeNotReady };

/// Debug's Fil-C step runs at `-O1` like every mode since 2026-10-01. From 2026-09-23 it ran at
/// `-O0`, because Debug IR segfaulted Fil-C's pass at `-O1` (KI-4). The cause is Fil-C's
/// `indirectbr` lowering, which breaks phis when a function has several `indirectbr`s (Zig emits
/// one per `continue :label`). zilc's patched Fil-C clang fixes it (`tools/filc/`). `-O0` was not
/// free: it left syscall pointer arguments without capabilities (KI-19) and made Fil-C's pass
/// several times slower (KI-22). With the prebuilt clang, Debug builds now fail on KI-4.
pub fn isDebug(optimize: []const u8) bool {
    return std.mem.eql(u8, optimize, "Debug");
}

/// The generated entry module. It is the root; the user's file is a module
/// named `user`, so Zig never pulls in `start.zig`.
const entry_shim =
    \\// Generated by zilc. Do not edit; edit src/driver.zig.
    \\//
    \\// Zig's start.zig cannot run under Fil-C: it forges a pointer from
    \\// getauxval(AT_PHDR) to read the program headers, and a pointer made from
    \\// an integer has no capability, so the first read traps. This shim gives
    \\// Fil-C's musl a plain C `main` to call instead.
    \\const std = @import("std");
    \\const user = @import("user");
    \\
    \\// Zig's default panic handler prints a stack trace by capturing the CPU
    \\// registers with inline asm (std.debug's getcontext), which can never carry
    \\// capabilities, so Fil-C rightly refuses it. The root module may replace the
    \\// handler, and this shim is the root, so panics report through Fil-C instead:
    \\// zerror prints the message and stops the program the same way a memory-safety
    \\// violation does, with Fil-C's own stack trace (KI-7, design-decisions.md
    \\// invariant 5).
    \\pub const panic = std.debug.FullPanic(zilcPanic);
    \\
    \\// std's page_allocator maps memory with mmap and passes the end of its previous
    \\// mapping as an address hint. Under Fil-C that hint is a pointer one past an
    \\// object's end, which Fil-C's mmap rightly rejects (cmem/zig-upstream-notes.md
    \\// Z-2). std lets the root module supply the page allocator, so pages come from
    \\// Fil-C's malloc instead: real GC objects with exact capabilities.
    \\pub const os = struct {
    \\    pub const heap = struct {
    \\        pub const page_allocator = std.heap.c_allocator;
    \\    };
    \\};
    \\
    \\// std.crypto.random's thread-local CSPRNG first probes for QEMU by calling
    \\// madvise with a deliberately invalid advice (0xffffffff), expecting EINVAL.
    \\// Fil-C's madvise stops the program on an unrecognized advice instead of
    \\// returning EINVAL (cmem/workarounds.md KI-20). std's official option makes
    \\// every fill a getrandom call, through Fil-C's checked libc (directly, or via
    \\// zilc_syscall when std picks the raw syscall): the kernel's
    \\// CSPRNG, fork-safe by construction, and the madvise path is never reached.
    \\pub const std_options: std.Options = .{ .crypto_always_getrandom = true };
    \\
    \\extern fn zerror(str: [*:0]const u8) void;
    \\
    \\fn zilcPanic(msg: []const u8, first_trace_addr: ?usize) noreturn {
    \\    _ = first_trace_addr;
    \\    var buf: [1024]u8 = undefined;
    \\    const text = std.fmt.bufPrintZ(&buf, "zig panic: {s}", .{msg}) catch "zig panic (message too long)";
    \\    zerror(text);
    \\    std.process.abort(); // zerror does not return; this only satisfies `noreturn`
    \\}
    \\
    \\export fn main(argc: c_int, argv: [*][*:0]u8) c_int {
    \\    std.os.argv = argv[0..@intCast(argc)];
    \\
    \\    const Ret = @typeInfo(@TypeOf(user.main)).@"fn".return_type.?;
    \\    switch (@typeInfo(Ret)) {
    \\        .void => {
    \\            user.main();
    \\            return 0;
    \\        },
    \\        .int => return user.main(),
    \\        .error_union => {
    \\            const payload = @typeInfo(Ret).error_union.payload;
    \\            if (user.main()) |value| {
    \\                return if (payload == void) 0 else value;
    \\            } else |err| {
    \\                std.debug.print("error: {s}\n", .{@errorName(err)});
    \\                return 1;
    \\            }
    \\        },
    \\        else => @compileError("zilc: main must return void, !void, u8 or !u8"),
    \\    }
    \\}
    \\
;

/// The helper that Zig's raw `syscall` asm is redirected to (ir.rewriteSyscalls,
/// KI-7). It is compiled by Fil-C, so it is checked code reaching the kernel only
/// through Fil-C's libc, which also tells the GC before blocking.
///
/// Every argument arrives as a pointer, so a real pointer (a futex word, a
/// timespec) keeps its capability. It returns the kernel's convention, -errno
/// on failure, because that is what the Zig code around the asm expects.
///
/// Fil-C's generic `syscall()` handles some numbers (gettid, futex) but rejects
/// others ("unsupported syscall: 230"), so those go to their libc function.
/// Measured 2026-09-30 by tools/p3/syscall-probe.c.
const syscall_helper_c =
    \\// Generated by zilc: raw system calls from Zig's std, routed through Fil-C's libc.
    \\#define _GNU_SOURCE
    \\#include <errno.h>
    \\#include <sys/syscall.h>
    \\#include <time.h>
    \\#include <unistd.h>
    \\
    \\long zilc_syscall(long n, void *a1, void *a2, void *a3, void *a4, void *a5, void *a6) {
    \\    long r;
    \\    switch (n) {
    \\    case SYS_clock_nanosleep: {
    \\        // Rejected by Fil-C's generic syscall(); libc's returns an errno value.
    \\        int e = clock_nanosleep((clockid_t)(long)a1, (int)(long)a2, a3, a4);
    \\        return e ? -e : 0;
    \\    }
    \\    case SYS_futex:
    \\        // Fil-C emulates futexes in user space; the word and timeout keep their capabilities.
    \\        r = syscall(SYS_futex, a1, (long)a2, (long)a3, a4, a5, (long)a6);
    \\        break;
    \\    default:
    \\        r = syscall(n, a1, a2, a3, a4, a5, a6);
    \\        break;
    \\    }
    \\    return r == -1 ? -errno : r;
    \\}
    \\
;

/// Zig's compiler-rt files implementing 128-bit float (`f128`) arithmetic (KI-9).
/// LLVM lowers f128 operations to calls into these, but compiler-rt is never
/// compiled through the pass, so under Fil-C nothing checked provides them. When
/// a program uses f128, zilc compiles these files through the same pipeline as
/// the program, so they are checked code too.
const f128_rt_files = [_][]const u8{
    "addtf3",     "subtf3",      "multf3",      "divtf3",      "cmptf2",      "getf2",
    "unordtf2",   "extendsftf2", "extenddftf2", "trunctfsf2",  "trunctfdf2",  "fixtfsi",
    "fixtfdi",    "fixtfti",     "fixunstfsi",  "fixunstfdi",  "fixunstfti",  "floatsitf",
    "floatditf",  "floattitf",   "floatunsitf", "floatunditf", "floatuntitf", "extendxftf2",
    "trunctfxf2", "round",
};

/// The only symbols those files may export. Everything else is made internal,
/// so that, for example, round.zig's `round` and `roundf` cannot displace Fil-C's
/// own libm functions for C code linked into the same program.
const f128_rt_exports = [_][]const u8{
    "__addtf3",    "__subtf3",     "__multf3",     "__divtf3",     "__cmptf2",     "__eqtf2",
    "__netf2",     "__lttf2",      "__letf2",      "__getf2",      "__gttf2",      "__unordtf2",
    "__extendsftf2", "__extenddftf2", "__trunctfsf2", "__trunctfdf2", "__fixtfsi",  "__fixtfdi",
    "__fixtfti",   "__fixunstfsi", "__fixunstfdi", "__fixunstfti", "__floatsitf",  "__floatditf",
    "__floattitf", "__floatunsitf", "__floatunditf", "__floatuntitf", "__extendxftf2",
    "__trunctfxf2", "roundq",
};

/// What zilc needs from `zig env` (ZON: `.lib_dir = "…"`, `.version = "…"`).
const ZigEnv = struct {
    lib_dir: []u8,
    version: []u8,
    fn deinit(self: ZigEnv, gpa: std.mem.Allocator) void {
        gpa.free(self.lib_dir);
        gpa.free(self.version);
    }
};

fn zigEnv(gpa: std.mem.Allocator, zig: []const u8) !ZigEnv {
    const res = try std.process.Child.run(.{ .allocator = gpa, .argv = &.{ zig, "env" } });
    defer gpa.free(res.stdout);
    defer gpa.free(res.stderr);
    const lib_dir = try zonString(gpa, res.stdout, ".lib_dir = \"");
    errdefer gpa.free(lib_dir);
    return .{ .lib_dir = lib_dir, .version = try zonString(gpa, res.stdout, ".version = \"") };
}

fn zonString(gpa: std.mem.Allocator, zon: []const u8, key: []const u8) ![]u8 {
    const start = (std.mem.indexOf(u8, zon, key) orelse return Error.ToolFailed) + key.len;
    const end = std.mem.indexOfScalarPos(u8, zon, start, '"') orelse return Error.ToolFailed;
    // ZON escapes backslashes (Windows paths); Linux paths come through unchanged.
    return std.mem.replaceOwned(u8, gpa, zon[start..end], "\\\\", "\\");
}

/// zilc's cache: $ZILC_CACHE_DIR, else $XDG_CACHE_HOME/zilc, else $HOME/.cache/zilc.
fn cacheRoot(gpa: std.mem.Allocator) ![]u8 {
    if (std.process.getEnvVarOwned(gpa, "ZILC_CACHE_DIR")) |d| return d else |_| {}
    if (std.process.getEnvVarOwned(gpa, "XDG_CACHE_HOME")) |d| {
        defer gpa.free(d);
        return std.fmt.allocPrint(gpa, "{s}/zilc", .{d});
    } else |_| {}
    const home = std.process.getEnvVarOwned(gpa, "HOME") catch return Error.ToolFailed;
    defer gpa.free(home);
    return std.fmt.allocPrint(gpa, "{s}/.cache/zilc", .{home});
}

/// Does this Zig file look like a program (rather than a library of exports)?
///
/// Textual, deliberately: parsing Zig to answer it would be a compiler, and a
/// wrong guess is cheap to override with `--entry`.
fn declaresMain(gpa: std.mem.Allocator, path: []const u8) bool {
    const src = std.fs.cwd().readFileAlloc(gpa, path, 16 * 1024 * 1024) catch return false;
    defer gpa.free(src);
    return std.mem.indexOf(u8, src, "pub fn main(") != null;
}

/// What a given input file needs: Zig compiles it to IR first, or Fil-C takes it directly.
fn classify(path: []const u8) !enum { zig, native } {
    const ext = std.fs.path.extension(path);
    if (std.mem.eql(u8, ext, ".zig")) return .zig;
    inline for (.{ ".c", ".cc", ".cpp", ".cxx", ".o", ".a", ".s", ".ll" }) |known| {
        if (std.mem.eql(u8, ext, known)) return .native;
    }
    return Error.UnsupportedInput;
}

fn run(gpa: std.mem.Allocator, argv: []const []const u8, verbose: bool) !void {
    if (verbose) {
        for (argv, 0..) |a, i| std.debug.print("{s}{s}", .{ if (i == 0) "+ " else " ", a });
        std.debug.print("\n", .{});
    }
    var child = std.process.Child.init(argv, gpa);
    child.stdin_behavior = .Inherit;
    child.stdout_behavior = .Inherit;
    child.stderr_behavior = .Inherit;
    const term = child.spawnAndWait() catch |e| {
        std.debug.print("zilc: cannot run '{s}': {s}\n", .{ argv[0], @errorName(e) });
        return Error.ToolFailed;
    };
    switch (term) {
        .Exited => |code| if (code != 0) {
            std.debug.print("zilc: '{s}' exited with {d}\n", .{ argv[0], code });
            return Error.ToolFailed;
        },
        else => {
            std.debug.print("zilc: '{s}' terminated abnormally\n", .{argv[0]});
            return Error.ToolFailed;
        },
    }
}

/// Zig source → LLVM IR → Fil-C-dialect IR → object file. Returns the object path.
fn compileZig(
    gpa: std.mem.Allocator,
    opts: Options,
    tmp_path: []const u8,
    src: []const u8,
    /// Wrap this file in the generated entry shim, so it can own `main`.
    is_entry: bool,
    /// Set if this module's raw `syscall` asm was redirected to `zilc_syscall`,
    /// so the link needs the helper (KI-7).
    needs_syscall_helper: *bool,
    /// Set if this module uses 128-bit floats, so the link needs the f128
    /// compiler-rt helpers (KI-9).
    uses_f128: *bool,
    /// If set, every function definition not named here is made internal.
    keep_exports: ?[]const []const u8,
    /// The std overlay with zilc's backports, if this Zig version has any (KI-11).
    zig_lib_dir: ?[]const u8,
) ![]u8 {
    const stem = std.fs.path.stem(src);
    const ll_path = try std.fmt.allocPrint(gpa, "{s}/{s}.ll", .{ tmp_path, stem });
    defer gpa.free(ll_path);
    const filc_ll_path = try std.fmt.allocPrint(gpa, "{s}/{s}.filc.ll", .{ tmp_path, stem });
    defer gpa.free(filc_ll_path);
    const obj_path = try std.fmt.allocPrint(gpa, "{s}/{s}.o", .{ tmp_path, stem });
    errdefer gpa.free(obj_path);

    // 1. Stock Zig emits plain LLVM IR. `-fno-emit-bin`: we only want the IR.
    //
    // Zig's UNOPTIMIZED module (KI-17), the default since 2026-09-30. `-femit-llvm-ir`
    // is post-optimization, and LLVM's optimizer runs there under Zig's integral data
    // layout, so it may rewrite pointer loads as `load i64` + `inttoptr`, which loses
    // capabilities under Fil-C. Fil-C's own pipeline optimizes only under `ni:0`,
    // which forbids exactly that. With this route the three Release modes give
    // identical corpus results. ZILC_OPTIMIZED_IR=1 restores the old route, for
    // comparison only.
    const unopt = blk: {
        const v = std.process.getEnvVarOwned(gpa, "ZILC_OPTIMIZED_IR") catch break :blk true;
        defer gpa.free(v);
        break :blk !std.mem.eql(u8, v, "1");
    };
    const emit_arg = if (unopt)
        try std.fmt.allocPrint(gpa, "--verbose-llvm-ir={s}", .{ll_path})
    else
        try std.fmt.allocPrint(gpa, "-femit-llvm-ir={s}", .{ll_path});
    defer gpa.free(emit_arg);

    var zig_args: std.ArrayListUnmanaged([]const u8) = .{};
    defer zig_args.deinit(gpa);
    try zig_args.appendSlice(gpa, &.{
        opts.zig,  "build-obj",
        "-target", opts.target,
        "-O",      opts.optimize,
        "-fno-emit-bin", emit_arg,
        // Always: Fil-C always links its libc, and without -lc Zig's std reaches
        // the kernel through raw `syscall` asm in many more places (KI-7).
        "-lc",
        // Debug defaults to Valgrind client requests: a magic asm sequence that is a
        // no-op unless running under Valgrind. Fil-C refuses all inline asm, and a
        // zilc program never runs under Valgrind, so leave them out (KI-14).
        "-fno-valgrind",
        // Always the LLVM backend. Debug otherwise defaults to Zig's own x86_64
        // backend, which emits no LLVM module at all (`-femit-llvm-ir` used to
        // force LLVM implicitly; the unoptimized route does not, KI-17).
        "-fllvm",
    });
    if (zig_lib_dir) |d| try zig_args.appendSlice(gpa, &.{ "--zig-lib-dir", d });
    // Every mode, not only Debug: ReleaseSafe emits the probe too for large frames
    // (std.debug's stack-trace code, std.fs path buffers), and it fails the link the
    // same way. Fil-C checks the stack at every function entry anyway (KI-8).
    try zig_args.append(gpa, "-fno-stack-check");

    var shim_path: ?[]u8 = null;
    defer if (shim_path) |p| gpa.free(p);

    if (is_entry) {
        // The shim is the ROOT and the user's file is a module, which is what
        // keeps `start.zig` out of the build entirely.
        const p = try std.fmt.allocPrint(gpa, "{s}/zilc_entry.zig", .{tmp_path});
        shim_path = p;
        try std.fs.cwd().writeFile(.{ .sub_path = p, .data = entry_shim });

        const root_arg = try std.fmt.allocPrint(gpa, "-Mroot={s}", .{p});
        defer gpa.free(root_arg);
        const user_arg = try std.fmt.allocPrint(gpa, "-Muser={s}", .{src});
        defer gpa.free(user_arg);
        try zig_args.appendSlice(gpa, &.{ "--dep", "user", root_arg, user_arg });
        try run(gpa, zig_args.items, opts.verbose);
    } else {
        try zig_args.append(gpa, src);
        try run(gpa, zig_args.items, opts.verbose);
    }

    // 2. The rewrite: two lines, and the whole reason this driver exists.
    const plain = try std.fs.cwd().readFileAlloc(gpa, ll_path, 512 * 1024 * 1024);
    defer gpa.free(plain);
    const dialect = ir.toFilCDialect(gpa, plain) catch |e| {
        std.debug.print("zilc: cannot rewrite IR for '{s}': {s}\n", .{ src, @errorName(e) });
        return Error.ToolFailed;
    };
    defer gpa.free(dialect);
    // 2b. Zig's raw `syscall` asm, which Fil-C refuses, goes through the checked libc (KI-7).
    const routed = try ir.rewriteSyscalls(gpa, dialect);
    defer gpa.free(routed.ir);
    if (routed.count > 0) {
        needs_syscall_helper.* = true;
        if (opts.verbose) std.debug.print("zilc: {s}: {d} raw syscall(s) routed through {s}\n", .{ src, routed.count, ir.syscall_helper });
    }
    // 2c. Overflow-checked `+ - *` hide pointer arithmetic from Fil-C's capability
    // recovery; expose the (identical) plain result (KI-13).
    const folded = try ir.foldOverflowValues(gpa, routed.ir);
    defer gpa.free(folded.ir);
    if (opts.verbose and folded.count > 0) std.debug.print("zilc: {s}: {d} overflow-checked result(s) exposed as plain arithmetic\n", .{ src, folded.count });

    // 2d. Fil-C's pass asserts on a global of a 3-byte type (i17..i24, <3 x i8>); wrap its value (KI-18).
    const wrapped = try ir.wrapThreeByteGlobals(gpa, folded.ir);
    defer gpa.free(wrapped.ir);
    if (opts.verbose and wrapped.count > 0) std.debug.print("zilc: {s}: {d} 3-byte global(s) wrapped in a struct\n", .{ src, wrapped.count });

    if (std.mem.indexOf(u8, wrapped.ir, "fp128") != null) uses_f128.* = true;
    const final_ir = if (keep_exports) |keep| try ir.internalizeExcept(gpa, wrapped.ir, keep) else null;
    defer if (final_ir) |f| gpa.free(f);
    try std.fs.cwd().writeFile(.{ .sub_path = filc_ll_path, .data = final_ir orelse wrapped.ir });

    // 3. Fil-C's clang runs the pass and emits the object.
    try filcCompile(gpa, opts, tmp_path, stem, filc_ll_path, obj_path);
    return obj_path;
}

/// Modules whose Fil-C-dialect IR is at least this big get their code generation split into
/// parallel parts. Below it, the extra processes cost more than they save.
const split_min_bytes = 4 * 1024 * 1024;
/// The automatic job count's cap. Each part costs a clang process (up to ~0.75 GB on `69`), and
/// 32 parallel LLVM compiles once exhausted the 31 GB WSL VM (tools/filc/build-patched-clang.sh).
const max_auto_jobs = 16;

/// Fil-C's clang: Fil-C-dialect IR in, object out.
///
/// Big modules take three steps instead of one (build-speed lever (a), cmem/workarounds.md KI-22):
///  1. clang runs Fil-C's pass and the -O1 optimizer on the WHOLE module and stops at bitcode,
///     keeping use-list order (`-emit-llvm-uselists`), because x86 code generation depends on it.
///  2. zilc's mode of `llvm-split` (tools/filc/patch-split.ts) cuts that bitcode into parts by
///     deleting the other parts' bodies, one process per part, in parallel.
///  3. clang generates each part's code in parallel (`-disable-llvm-passes`: no pass, no
///     optimizer, the same code generation settings), `ld -r` joins the parts, and objcopy
///     makes the locals the cut exposed local again.
/// Every decision about the code is still made on the whole module, so the result is the same
/// code as one clang run: checked function by function on `69` (2,840 functions identical,
/// same global and undefined symbols, same stripped size). Step 1 alone took ~34 s of `69`'s
/// ~56 s; code generation went from ~22 s to ~7 s.
fn filcCompile(
    gpa: std.mem.Allocator,
    opts: Options,
    tmp_path: []const u8,
    stem: []const u8,
    filc_ll_path: []const u8,
    obj_path: []const u8,
) !void {
    const jobs: u32 = if (opts.jobs != 0) opts.jobs else @intCast(@min(std.Thread.getCpuCount() catch 1, max_auto_jobs));
    const size = (try std.fs.cwd().statFile(filc_ll_path)).size;
    const splitter = if (jobs >= 2 and size >= split_min_bytes) try toolPath(gpa, opts.filc, "llvm-split") else null;
    defer if (splitter) |s| gpa.free(s);
    if (splitter == null) {
        if (jobs >= 2 and size >= split_min_bytes and opts.verbose)
            std.debug.print("zilc: {s}: no llvm-split next to Fil-C's clang; one code generation job\n", .{stem});
        // `-Wno-override-module`: Zig names the triple `…-linux-musl` while Fil-C's
        // driver is `…-linux-gnu`, so clang warns that it is overriding ours. It is
        // expected, not a mismatch to fix — Fil-C's libc *is* musl whatever its
        // triple says, which is why the musl target is the one that links (KI-6).
        return runFilc(gpa, opts, &.{
            opts.filc, "-O1", "-g", "-Wno-override-module", "-c", "-o", obj_path, filc_ll_path,
        });
    }

    // 1. The pass and the optimizer, whole.
    const bc_path = try std.fmt.allocPrint(gpa, "{s}/{s}.opt.bc", .{ tmp_path, stem });
    defer gpa.free(bc_path);
    try runFilc(gpa, opts, &.{
        opts.filc,  "-O1", "-g", "-Wno-override-module", "-c", "-emit-llvm",
        "-Xclang", "-emit-llvm-uselists", "-o", bc_path, filc_ll_path,
    });

    // 2. The cut.
    const parts_dir = try std.fmt.allocPrint(gpa, "{s}/{s}.parts", .{ tmp_path, stem });
    defer gpa.free(parts_dir);
    try std.fs.cwd().makePath(parts_dir);
    const keep_path = try std.fmt.allocPrint(gpa, "{s}/keep-global.txt", .{parts_dir});
    defer gpa.free(keep_path);

    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const n_arg = try std.fmt.allocPrint(arena, "-j{d}", .{jobs});
    const keep_arg = try std.fmt.allocPrint(arena, "--zilc-keep-global={s}", .{keep_path});
    const cuts = try arena.alloc([]const []const u8, jobs);
    const gens = try arena.alloc([]const []const u8, jobs);
    const objs = try arena.alloc([]const u8, jobs);
    for (0..jobs) |i| {
        const bc = try std.fmt.allocPrint(arena, "{s}/part{d}.bc", .{ parts_dir, i });
        objs[i] = try std.fmt.allocPrint(arena, "{s}/part{d}.o", .{ parts_dir, i });
        const part_arg = try std.fmt.allocPrint(arena, "--zilc-part={d}", .{i});
        cuts[i] = try arena.dupe([]const u8, &.{ splitter.?, n_arg, part_arg, keep_arg, "-o", bc, bc_path });
        gens[i] = try arena.dupe([]const u8, &.{
            opts.filc, "-O1", "-g", "-Xclang", "-disable-llvm-passes", "-c", "-x", "ir", "-o", objs[i], bc,
        });
    }
    if (try runParallel(gpa, cuts, opts.verbose)) |code| {
        // 2 = a module shape the cut does not handle; it said which. Generate the code whole.
        if (code != 2) {
            std.debug.print("zilc: llvm-split exited with {d}\n", .{code});
            return Error.ToolFailed;
        }
        return run(gpa, &.{
            opts.filc, "-O1", "-g", "-Xclang", "-disable-llvm-passes", "-c", "-x", "ir", "-o", obj_path, bc_path,
        }, opts.verbose);
    }

    // 3. Code generation per part, then one object again.
    if (try runParallel(gpa, gens, opts.verbose)) |code| {
        std.debug.print("zilc: Fil-C's clang exited with {d} generating a part's code\n", .{code});
        return Error.ToolFailed;
    }
    // Fil-C's clang driver adds its crt object even to `-r -nostdlib`, so the linker is run
    // directly: the same one clang links with.
    const ld = try toolPath(gpa, opts.filc, "ld") orelse try gpa.dupe(u8, "ld");
    defer gpa.free(ld);
    const objcopy = try toolPath(gpa, opts.filc, "objcopy") orelse try gpa.dupe(u8, "objcopy");
    defer gpa.free(objcopy);
    const joined = try std.fmt.allocPrint(arena, "{s}/joined.o", .{parts_dir});
    var ld_args: std.ArrayListUnmanaged([]const u8) = .{};
    try ld_args.appendSlice(arena, &.{ ld, "-r", "-o", joined });
    try ld_args.appendSlice(arena, objs);
    try run(gpa, ld_args.items, opts.verbose);
    // The cut made locals used across parts hidden globals; everything the input did not
    // define as global becomes local again. (A list of the input's globals, not of the exposed
    // locals: Zig names contain spaces, which objcopy's symbol files cannot hold.)
    const keep_flag = try std.fmt.allocPrint(arena, "--keep-global-symbols={s}", .{keep_path});
    try run(gpa, &.{ objcopy, keep_flag, joined, obj_path }, opts.verbose);
    if (opts.verbose) std.debug.print("zilc: {s}: code generated in {d} parallel parts\n", .{ stem, jobs });
}

/// Runs Fil-C's clang on Fil-C-dialect IR, which is where its pass runs.
fn runFilc(gpa: std.mem.Allocator, opts: Options, argv: []const []const u8) !void {
    run(gpa, argv, opts.verbose) catch |e| {
        if (isDebug(opts.optimize)) std.debug.print(
            \\zilc: Debug builds need zilc's patched Fil-C clang, which fixes Fil-C's crash on
            \\  several indirectbr in one function (cmem/known-issues.md KI-4; tools/filc/).
            \\
        , .{});
        return e;
    };
}

/// A tool from Fil-C's toolchain, the way its clang finds it (its own directory first, then
/// PATH). Null if clang only echoes the bare name back, i.e. found nowhere it looked.
fn toolPath(gpa: std.mem.Allocator, filc: []const u8, name: []const u8) !?[]u8 {
    const flag = try std.fmt.allocPrint(gpa, "-print-prog-name={s}", .{name});
    defer gpa.free(flag);
    const res = std.process.Child.run(.{ .allocator = gpa, .argv = &.{ filc, flag } }) catch return null;
    defer gpa.free(res.stdout);
    defer gpa.free(res.stderr);
    const path = std.mem.trim(u8, res.stdout, " \t\r\n");
    if (std.mem.indexOfScalar(u8, path, '/') == null) return null;
    return try gpa.dupe(u8, path);
}

/// Runs every command at once and waits for all. Null if all exited 0, else the first
/// non-zero exit code in command order (so the result does not depend on timing).
fn runParallel(gpa: std.mem.Allocator, cmds: []const []const []const u8, verbose: bool) !?u8 {
    const children = try gpa.alloc(std.process.Child, cmds.len);
    defer gpa.free(children);
    var started: usize = 0;
    var spawn_error: ?anyerror = null;
    for (cmds, 0..) |argv, i| {
        if (verbose) {
            for (argv, 0..) |a, k| std.debug.print("{s}{s}", .{ if (k == 0) "+ " else " ", a });
            std.debug.print(" &\n", .{});
        }
        children[i] = std.process.Child.init(argv, gpa);
        children[i].stdin_behavior = .Ignore;
        children[i].stdout_behavior = .Inherit;
        // Every part reports the same refusal; one copy is enough.
        children[i].stderr_behavior = if (i == 0) .Inherit else .Ignore;
        children[i].spawn() catch |e| {
            spawn_error = e;
            break;
        };
        started += 1;
    }
    var first: ?u8 = null;
    var abnormal = false;
    for (children[0..started]) |*c| {
        const term = c.wait() catch {
            abnormal = true;
            continue;
        };
        switch (term) {
            .Exited => |code| if (code != 0 and first == null) {
                first = code;
            },
            else => abnormal = true,
        }
    }
    if (spawn_error) |e| {
        std.debug.print("zilc: cannot run '{s}': {s}\n", .{ cmds[started][0], @errorName(e) });
        return Error.ToolFailed;
    }
    if (abnormal) {
        std.debug.print("zilc: '{s}' terminated abnormally\n", .{cmds[0][0]});
        return Error.ToolFailed;
    }
    return first;
}

pub fn build(gpa: std.mem.Allocator, opts: Options) !void {
    if (opts.inputs.len == 0) return Error.NoInputs;
    if (opts.runtime == .zig) {
        std.debug.print(
            \\zilc: --runtime zig is reserved: the Zig runtime is not ready for testing
            \\  yet (cmem/roadmap.md P3). Use --runtime filc, the default.
            \\
        , .{});
        return Error.RuntimeNotReady;
    }

    // Temps live beside the output so a failed build leaves them inspectable
    // with --keep-temps, which is how KI-4/KI-5 were diagnosed in the first place.
    const tmp_path = try std.fmt.allocPrint(gpa, "{s}.zilc-tmp", .{opts.output});
    defer gpa.free(tmp_path);
    try std.fs.cwd().makePath(tmp_path);
    defer if (!opts.keep_temps) {
        std.fs.cwd().deleteTree(tmp_path) catch {};
    } else std.debug.print("zilc: kept intermediates in {s}/\n", .{tmp_path});

    var link_args: std.ArrayListUnmanaged([]const u8) = .{};
    defer link_args.deinit(gpa);
    var owned: std.ArrayListUnmanaged([]u8) = .{};
    defer {
        for (owned.items) |p| gpa.free(p);
        owned.deinit(gpa);
    }

    try link_args.appendSlice(gpa, &.{ opts.filc, "-O1", "-g" });

    // Which input owns `main`? In `.auto`, a lone Zig file declaring `pub fn main`
    // with no C/C++ beside it gets the generated entry shim; anything else
    // assumes C owns `main`, which is the shape the interop example uses.
    var entry_index: ?usize = null;
    if (opts.entry != .c and opts.emit == .exe) {
        var has_native = false;
        for (opts.inputs) |input| {
            if ((try classify(input)) == .native) has_native = true;
        }
        for (opts.inputs, 0..) |input, i| {
            if ((try classify(input)) != .zig) continue;
            const wants = switch (opts.entry) {
                .zig => true,
                .auto => !has_native and declaresMain(gpa, input),
                .c => false,
            };
            if (wants) {
                entry_index = i;
                break;
            }
        }
        if (opts.entry == .zig and entry_index == null) {
            std.debug.print("zilc: --entry zig, but no .zig input was given\n", .{});
            return Error.NoInputs;
        }
    }

    // Zig's own std, with zilc's backports for this exact version, if it has any (KI-11).
    var env: ?ZigEnv = null;
    defer if (env) |e| e.deinit(gpa);
    var overlay: ?[]u8 = null;
    defer if (overlay) |o| gpa.free(o);
    for (opts.inputs) |input| {
        if ((try classify(input)) != .zig) continue;
        env = try zigEnv(gpa, opts.zig);
        const cache = try cacheRoot(gpa);
        defer gpa.free(cache);
        overlay = ir_std.ensureOverlay(gpa, env.?.lib_dir, env.?.version, cache) catch |e| {
            std.debug.print("zilc: cannot prepare the std backports for Zig {s}: {s}\n" ++
                "  (each patch checks the exact original it replaces; see cmem/known-issues.md KI-11)\n", .{ env.?.version, @errorName(e) });
            return Error.ToolFailed;
        };
        if (opts.verbose) if (overlay) |o| std.debug.print("zilc: std backports for Zig {s}: {s}\n", .{ env.?.version, o });
        break;
    }

    var needs_syscall_helper = false;
    var uses_f128 = false;
    for (opts.inputs, 0..) |input, i| {
        switch (try classify(input)) {
            .zig => {
                const obj = try compileZig(gpa, opts, tmp_path, input, entry_index == i, &needs_syscall_helper, &uses_f128, null, overlay);
                try owned.append(gpa, obj);
                try link_args.append(gpa, obj);
            },
            // C/C++/objects go to Fil-C untouched: it is already their compiler.
            .native => try link_args.append(gpa, input),
        }
    }

    // 128-bit floats: the compiler-rt helpers, compiled through the pass (KI-9).
    if (uses_f128) {
        const lib_dir = env.?.lib_dir; // set: uses_f128 implies a Zig input
        // Their own subdirectory, so a user file named like one (round.zig) cannot collide.
        const rt_tmp = try std.fmt.allocPrint(gpa, "{s}/compiler_rt", .{tmp_path});
        defer gpa.free(rt_tmp);
        try std.fs.cwd().makePath(rt_tmp);
        if (opts.verbose) std.debug.print("zilc: f128 in use: compiling {d} compiler-rt files through Fil-C\n", .{f128_rt_files.len});
        var unused = false;
        for (f128_rt_files) |name| {
            const src = try std.fmt.allocPrint(gpa, "{s}/compiler_rt/{s}.zig", .{ lib_dir, name });
            defer gpa.free(src);
            const obj = try compileZig(gpa, opts, rt_tmp, src, false, &needs_syscall_helper, &unused, &f128_rt_exports, overlay);
            try owned.append(gpa, obj);
            try link_args.append(gpa, obj);
        }
    }

    // One helper object for every module whose raw syscalls were redirected (KI-7).
    var helper_obj: ?[]u8 = null;
    defer if (helper_obj) |p| gpa.free(p);
    if (needs_syscall_helper) {
        const c_path = try std.fmt.allocPrint(gpa, "{s}/{s}.c", .{ tmp_path, ir.syscall_helper });
        defer gpa.free(c_path);
        const o_path = try std.fmt.allocPrint(gpa, "{s}/{s}.o", .{ tmp_path, ir.syscall_helper });
        helper_obj = o_path;
        try std.fs.cwd().writeFile(.{ .sub_path = c_path, .data = syscall_helper_c });
        try run(gpa, &.{ opts.filc, "-O1", "-g", "-c", "-o", o_path, c_path }, opts.verbose);
        try link_args.append(gpa, o_path);
    }

    if (opts.emit == .obj) {
        // Object-only: the .o files are the product, so copy them out.
        for (owned.items) |obj| {
            try std.fs.cwd().copyFile(obj, std.fs.cwd(), opts.output, .{});
        }
        if (helper_obj) |o| {
            // Without it the final link fails on `zilc_syscall`; hand it over beside the output.
            const dest = try std.fmt.allocPrint(gpa, "{s}.{s}.o", .{ opts.output, ir.syscall_helper });
            defer gpa.free(dest);
            try std.fs.cwd().copyFile(o, std.fs.cwd(), dest, .{});
            std.debug.print("zilc: note: also link {s} (raw syscalls routed through Fil-C's libc)\n", .{dest});
        }
        return;
    }

    try link_args.appendSlice(gpa, &.{ "-o", opts.output });
    try run(gpa, link_args.items, opts.verbose);
}

test "--runtime zig is refused before anything runs" {
    // No tool is invoked and no temp dir is made: the refusal comes first,
    // so the paths here never need to exist.
    try std.testing.expectError(Error.RuntimeNotReady, build(std.testing.allocator, .{
        .inputs = &.{"never-read.zig"},
        .output = "never-written",
        .runtime = .zig,
        .zig = "zig",
        .filc = "clang",
    }));
}
