// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT
//! The zilc compile pipeline.
//!
//!   .zig  --zig build-obj--> LLVM IR --rewrite--> Fil-C dialect IR --+
//!                                                                    |--filc clang--> safe binary
//!   .c/.cpp/.o/.a -----------------------------------------------------+
//!
//! Nothing here patches Zig or LLVM: stock Zig emits the IR, `ir.zig` rewrites
//! two lines of it, and Fil-C's clang runs the GIMSO pass and links.
//! Background and limits: cmem/roadmap.md P2, cmem/known-issues.md KI-4…KI-6.

const std = @import("std");
// Through the module, not the file: importing "ir.zig" directly would put the
// same file in two modules, which Zig rejects.
const ir = @import("zilc").ir;

/// Who provides `main`.
///
/// Zig's own start code cannot run under Fil-C: it does
/// `@ptrFromInt(getauxval(AT_PHDR))` to find the program headers, and a pointer
/// forged from an integer carries no capability, so the first read of it traps
/// (KI-5). `.zig` therefore generates a C-ABI `main` that calls the user's
/// `main` directly, and Zig's `start.zig` never enters the build.
pub const Entry = enum { auto, c, zig };

pub const Options = struct {
    inputs: []const []const u8,
    output: []const u8,
    entry: Entry = .auto,
    /// Zig optimize mode. ⚠️ Debug IR crashes the pass today (KI-4).
    optimize: []const u8 = "ReleaseSafe",
    /// ⚠️ Fil-C's libc is musl; a gnu target fails to link on `*64` symbols (KI-6).
    target: []const u8 = "x86_64-linux-musl",
    /// Emit a linked executable, or stop at objects.
    emit: enum { exe, obj } = .exe,
    zig: []const u8,
    filc: []const u8,
    keep_temps: bool = false,
    verbose: bool = false,
};

pub const Error = error{ ToolFailed, NoInputs, UnsupportedInput };

/// Debug needs two concessions, both measured 2026-09-23 (KI-4):
///
///  * **`filc -O0`.** Debug IR segfaults Fil-C's pass at `-O1`/`-O2` and compiles
///    fine at `-O0`. The crash is upstream's, in the optimizer's interaction
///    with the pass, and we cannot fix it from here.
///  * **`-fno-stack-check`.** Zig's stack probe (`__zig_probe_stack`) lives in
///    Zig's compiler-rt, which never goes through the pass, so the link fails
///    on it. Turning probing off is honest here: Fil-C's own checks are what
///    make the program safe, and they do not rely on guard pages.
///
/// The cost is size — a Debug object runs to tens of megabytes.
pub fn isDebug(optimize: []const u8) bool {
    return std.mem.eql(u8, optimize, "Debug");
}

/// The generated entry module. It is the root; the user's file is a module
/// named `user`, so Zig never pulls in `start.zig`.
const entry_shim =
    \\// Generated by zilc. Do not edit; edit src/driver.zig.
    \\//
    \\// Zig's start.zig cannot run under Fil-C: it forges a pointer from
    \\// getauxval(AT_PHDR) to read the program headers, and a pointer made from
    \\// an integer has no capability, so the first read traps. This shim gives
    \\// Fil-C's musl a plain C `main` to call instead.
    \\const std = @import("std");
    \\const user = @import("user");
    \\
    \\export fn main(argc: c_int, argv: [*][*:0]u8) c_int {
    \\    std.os.argv = argv[0..@intCast(argc)];
    \\
    \\    const Ret = @typeInfo(@TypeOf(user.main)).@"fn".return_type.?;
    \\    switch (@typeInfo(Ret)) {
    \\        .void => {
    \\            user.main();
    \\            return 0;
    \\        },
    \\        .int => return user.main(),
    \\        .error_union => {
    \\            const payload = @typeInfo(Ret).error_union.payload;
    \\            if (user.main()) |value| {
    \\                return if (payload == void) 0 else value;
    \\            } else |err| {
    \\                std.debug.print("error: {s}\n", .{@errorName(err)});
    \\                return 1;
    \\            }
    \\        },
    \\        else => @compileError("zilc: main must return void, !void, u8 or !u8"),
    \\    }
    \\}
    \\
;

/// Does this Zig file look like a program (rather than a library of exports)?
///
/// Textual, deliberately: parsing Zig to answer it would be a compiler, and a
/// wrong guess is cheap to override with `--entry`.
fn declaresMain(gpa: std.mem.Allocator, path: []const u8) bool {
    const src = std.fs.cwd().readFileAlloc(gpa, path, 16 * 1024 * 1024) catch return false;
    defer gpa.free(src);
    return std.mem.indexOf(u8, src, "pub fn main(") != null;
}

/// What a given input file needs: Zig compiles it to IR first, or Fil-C takes it directly.
fn classify(path: []const u8) !enum { zig, native } {
    const ext = std.fs.path.extension(path);
    if (std.mem.eql(u8, ext, ".zig")) return .zig;
    inline for (.{ ".c", ".cc", ".cpp", ".cxx", ".o", ".a", ".s", ".ll" }) |known| {
        if (std.mem.eql(u8, ext, known)) return .native;
    }
    return Error.UnsupportedInput;
}

fn run(gpa: std.mem.Allocator, argv: []const []const u8, verbose: bool) !void {
    if (verbose) {
        for (argv, 0..) |a, i| std.debug.print("{s}{s}", .{ if (i == 0) "+ " else " ", a });
        std.debug.print("\n", .{});
    }
    var child = std.process.Child.init(argv, gpa);
    child.stdin_behavior = .Inherit;
    child.stdout_behavior = .Inherit;
    child.stderr_behavior = .Inherit;
    const term = child.spawnAndWait() catch |e| {
        std.debug.print("zilc: cannot run '{s}': {s}\n", .{ argv[0], @errorName(e) });
        return Error.ToolFailed;
    };
    switch (term) {
        .Exited => |code| if (code != 0) {
            std.debug.print("zilc: '{s}' exited with {d}\n", .{ argv[0], code });
            return Error.ToolFailed;
        },
        else => {
            std.debug.print("zilc: '{s}' terminated abnormally\n", .{argv[0]});
            return Error.ToolFailed;
        },
    }
}

/// Zig source → LLVM IR → Fil-C-dialect IR → object file. Returns the object path.
fn compileZig(
    gpa: std.mem.Allocator,
    opts: Options,
    tmp_path: []const u8,
    src: []const u8,
    /// Wrap this file in the generated entry shim, so it can own `main`.
    is_entry: bool,
) ![]u8 {
    const stem = std.fs.path.stem(src);
    const ll_path = try std.fmt.allocPrint(gpa, "{s}/{s}.ll", .{ tmp_path, stem });
    defer gpa.free(ll_path);
    const filc_ll_path = try std.fmt.allocPrint(gpa, "{s}/{s}.filc.ll", .{ tmp_path, stem });
    defer gpa.free(filc_ll_path);
    const obj_path = try std.fmt.allocPrint(gpa, "{s}/{s}.o", .{ tmp_path, stem });
    errdefer gpa.free(obj_path);

    // 1. Stock Zig emits plain LLVM IR. `-fno-emit-bin`: we only want the IR.
    const emit_arg = try std.fmt.allocPrint(gpa, "-femit-llvm-ir={s}", .{ll_path});
    defer gpa.free(emit_arg);

    var zig_args: std.ArrayListUnmanaged([]const u8) = .{};
    defer zig_args.deinit(gpa);
    try zig_args.appendSlice(gpa, &.{
        opts.zig,  "build-obj",
        "-target", opts.target,
        "-O",      opts.optimize,
        "-fno-emit-bin", emit_arg,
    });
    if (isDebug(opts.optimize)) try zig_args.append(gpa, "-fno-stack-check");

    var shim_path: ?[]u8 = null;
    defer if (shim_path) |p| gpa.free(p);

    if (is_entry) {
        // The shim is the ROOT and the user's file is a module, which is what
        // keeps `start.zig` out of the build entirely.
        const p = try std.fmt.allocPrint(gpa, "{s}/zilc_entry.zig", .{tmp_path});
        shim_path = p;
        try std.fs.cwd().writeFile(.{ .sub_path = p, .data = entry_shim });

        const root_arg = try std.fmt.allocPrint(gpa, "-Mroot={s}", .{p});
        defer gpa.free(root_arg);
        const user_arg = try std.fmt.allocPrint(gpa, "-Muser={s}", .{src});
        defer gpa.free(user_arg);
        try zig_args.appendSlice(gpa, &.{ "-lc", "--dep", "user", root_arg, user_arg });
        try run(gpa, zig_args.items, opts.verbose);
    } else {
        try zig_args.append(gpa, src);
        try run(gpa, zig_args.items, opts.verbose);
    }

    // 2. The rewrite: two lines, and the whole reason this driver exists.
    const plain = try std.fs.cwd().readFileAlloc(gpa, ll_path, 512 * 1024 * 1024);
    defer gpa.free(plain);
    const dialect = ir.toFilCDialect(gpa, plain) catch |e| {
        std.debug.print("zilc: cannot rewrite IR for '{s}': {s}\n", .{ src, @errorName(e) });
        return Error.ToolFailed;
    };
    defer gpa.free(dialect);
    try std.fs.cwd().writeFile(.{ .sub_path = filc_ll_path, .data = dialect });

    // 3. Fil-C's clang runs the pass and emits the object.
    //
    // `-Wno-override-module`: Zig names the triple `…-linux-musl` while Fil-C's
    // driver is `…-linux-gnu`, so clang warns that it is overriding ours. It is
    // expected, not a mismatch to fix — Fil-C's libc *is* musl whatever its
    // triple says, which is why the musl target is the one that links (KI-6).
    const filc_opt: []const u8 = if (isDebug(opts.optimize)) "-O0" else "-O1";
    try run(gpa, &.{
        opts.filc, filc_opt, "-g", "-Wno-override-module", "-c", "-o", obj_path, filc_ll_path,
    }, opts.verbose);
    return obj_path;
}

pub fn build(gpa: std.mem.Allocator, opts: Options) !void {
    if (opts.inputs.len == 0) return Error.NoInputs;

    // Temps live beside the output so a failed build leaves them inspectable
    // with --keep-temps, which is how KI-4/KI-5 were diagnosed in the first place.
    const tmp_path = try std.fmt.allocPrint(gpa, "{s}.zilc-tmp", .{opts.output});
    defer gpa.free(tmp_path);
    try std.fs.cwd().makePath(tmp_path);
    defer if (!opts.keep_temps) {
        std.fs.cwd().deleteTree(tmp_path) catch {};
    } else std.debug.print("zilc: kept intermediates in {s}/\n", .{tmp_path});

    var link_args: std.ArrayListUnmanaged([]const u8) = .{};
    defer link_args.deinit(gpa);
    var owned: std.ArrayListUnmanaged([]u8) = .{};
    defer {
        for (owned.items) |p| gpa.free(p);
        owned.deinit(gpa);
    }

    try link_args.appendSlice(gpa, &.{ opts.filc, "-O1", "-g" });

    // Which input owns `main`? In `.auto`, a lone Zig file declaring `pub fn main`
    // with no C/C++ beside it gets the generated entry shim; anything else
    // assumes C owns `main`, which is the shape the interop example uses.
    var entry_index: ?usize = null;
    if (opts.entry != .c and opts.emit == .exe) {
        var has_native = false;
        for (opts.inputs) |input| {
            if ((try classify(input)) == .native) has_native = true;
        }
        for (opts.inputs, 0..) |input, i| {
            if ((try classify(input)) != .zig) continue;
            const wants = switch (opts.entry) {
                .zig => true,
                .auto => !has_native and declaresMain(gpa, input),
                .c => false,
            };
            if (wants) {
                entry_index = i;
                break;
            }
        }
        if (opts.entry == .zig and entry_index == null) {
            std.debug.print("zilc: --entry zig, but no .zig input was given\n", .{});
            return Error.NoInputs;
        }
    }

    for (opts.inputs, 0..) |input, i| {
        switch (try classify(input)) {
            .zig => {
                const obj = try compileZig(gpa, opts, tmp_path, input, entry_index == i);
                try owned.append(gpa, obj);
                try link_args.append(gpa, obj);
            },
            // C/C++/objects go to Fil-C untouched: it is already their compiler.
            .native => try link_args.append(gpa, input),
        }
    }

    if (opts.emit == .obj) {
        // Object-only: the .o files are the product, so copy them out.
        for (owned.items) |obj| {
            try std.fs.cwd().copyFile(obj, std.fs.cwd(), opts.output, .{});
        }
        return;
    }

    try link_args.appendSlice(gpa, &.{ "-o", opts.output });
    try run(gpa, link_args.items, opts.verbose);
}
