// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT
//! The zilc compile pipeline.
//!
//!   .zig  --zig build-obj--> LLVM IR --rewrite--> Fil-C dialect IR --+
//!                                                                    |--filc clang--> safe binary
//!   .c/.cpp/.o/.a -----------------------------------------------------+
//!
//! Nothing here patches Zig or LLVM: stock Zig emits the IR, `ir.zig` rewrites
//! two lines of it, and Fil-C's clang runs the GIMSO pass and links.
//! Background and limits: cmem/roadmap.md P2, cmem/known-issues.md KI-4…KI-6.

const std = @import("std");
// Through the module, not the file: importing "ir.zig" directly would put the
// same file in two modules, which Zig rejects.
const ir = @import("zilc").ir;

/// Who provides `main`.
///
/// Zig's own start code cannot run under Fil-C: it does
/// `@ptrFromInt(getauxval(AT_PHDR))` to find the program headers, and a pointer
/// forged from an integer carries no capability, so the first read of it traps
/// (KI-5). `.zig` therefore generates a C-ABI `main` that calls the user's
/// `main` directly, and Zig's `start.zig` never enters the build.
pub const Entry = enum { auto, c, zig };

/// Which runtime the program links.
///
///  * `.filc` — Fil-C's `libpizlo`, the runtime every gate run uses today.
///  * `.zig`  — zilc's own Zig runtime (P3), linked ahead of `libpizlo` so each
///    entry point it defines overrides Fil-C's and the rest fall through.
///    ⚠️ Reserved: it is refused until the runtime is ready for testing, so a
///    build can never claim the Zig runtime while silently linking Fil-C's.
pub const Runtime = enum { filc, zig };

pub const Options = struct {
    inputs: []const []const u8,
    output: []const u8,
    entry: Entry = .auto,
    /// Zig optimize mode. ⚠️ Debug IR crashes the pass today (KI-4).
    optimize: []const u8 = "ReleaseSafe",
    /// ⚠️ Fil-C's libc is musl; a gnu target fails to link on `*64` symbols (KI-6).
    target: []const u8 = "x86_64-linux-musl",
    /// Emit a linked executable, or stop at objects.
    emit: enum { exe, obj } = .exe,
    runtime: Runtime = .filc,
    zig: []const u8,
    filc: []const u8,
    keep_temps: bool = false,
    verbose: bool = false,
};

pub const Error = error{ ToolFailed, NoInputs, UnsupportedInput, RuntimeNotReady };

/// Debug needs two concessions, both measured 2026-09-23 (KI-4):
///
///  * **`filc -O0`.** Debug IR segfaults Fil-C's pass at `-O1`/`-O2` and compiles
///    fine at `-O0`. The crash is upstream's, in the optimizer's interaction
///    with the pass, and we cannot fix it from here.
///  * **`-fno-stack-check`.** Zig's stack probe (`__zig_probe_stack`) lives in
///    Zig's compiler-rt, which never goes through the pass, so the link fails
///    on it. Turning probing off is honest here: Fil-C's own checks are what
///    make the program safe, and they do not rely on guard pages. Since
///    2026-09-30 this applies in every mode, not only Debug (KI-8).
///
/// The cost is size — a Debug object runs to tens of megabytes.
pub fn isDebug(optimize: []const u8) bool {
    return std.mem.eql(u8, optimize, "Debug");
}

/// The generated entry module. It is the root; the user's file is a module
/// named `user`, so Zig never pulls in `start.zig`.
const entry_shim =
    \\// Generated by zilc. Do not edit; edit src/driver.zig.
    \\//
    \\// Zig's start.zig cannot run under Fil-C: it forges a pointer from
    \\// getauxval(AT_PHDR) to read the program headers, and a pointer made from
    \\// an integer has no capability, so the first read traps. This shim gives
    \\// Fil-C's musl a plain C `main` to call instead.
    \\const std = @import("std");
    \\const user = @import("user");
    \\
    \\// Zig's default panic handler prints a stack trace by capturing the CPU
    \\// registers with inline asm (std.debug's getcontext), which can never carry
    \\// capabilities, so Fil-C rightly refuses it. The root module may replace the
    \\// handler, and this shim is the root, so panics report through Fil-C instead:
    \\// zerror prints the message and stops the program the same way a memory-safety
    \\// violation does, with Fil-C's own stack trace (KI-7, design-decisions.md
    \\// invariant 5).
    \\pub const panic = std.debug.FullPanic(zilcPanic);
    \\
    \\// std's page_allocator maps memory with mmap and passes the end of its previous
    \\// mapping as an address hint. Under Fil-C that hint is a pointer one past an
    \\// object's end, which Fil-C's mmap rightly rejects (cmem/zig-upstream-notes.md
    \\// Z-2). std lets the root module supply the page allocator, so pages come from
    \\// Fil-C's malloc instead: real GC objects with exact capabilities.
    \\pub const os = struct {
    \\    pub const heap = struct {
    \\        pub const page_allocator = std.heap.c_allocator;
    \\    };
    \\};
    \\
    \\extern fn zerror(str: [*:0]const u8) void;
    \\
    \\fn zilcPanic(msg: []const u8, first_trace_addr: ?usize) noreturn {
    \\    _ = first_trace_addr;
    \\    var buf: [1024]u8 = undefined;
    \\    const text = std.fmt.bufPrintZ(&buf, "zig panic: {s}", .{msg}) catch "zig panic (message too long)";
    \\    zerror(text);
    \\    std.process.abort(); // zerror does not return; this only satisfies `noreturn`
    \\}
    \\
    \\export fn main(argc: c_int, argv: [*][*:0]u8) c_int {
    \\    std.os.argv = argv[0..@intCast(argc)];
    \\
    \\    const Ret = @typeInfo(@TypeOf(user.main)).@"fn".return_type.?;
    \\    switch (@typeInfo(Ret)) {
    \\        .void => {
    \\            user.main();
    \\            return 0;
    \\        },
    \\        .int => return user.main(),
    \\        .error_union => {
    \\            const payload = @typeInfo(Ret).error_union.payload;
    \\            if (user.main()) |value| {
    \\                return if (payload == void) 0 else value;
    \\            } else |err| {
    \\                std.debug.print("error: {s}\n", .{@errorName(err)});
    \\                return 1;
    \\            }
    \\        },
    \\        else => @compileError("zilc: main must return void, !void, u8 or !u8"),
    \\    }
    \\}
    \\
;

/// The helper that Zig's raw `syscall` asm is redirected to (ir.rewriteSyscalls,
/// KI-7). It is compiled by Fil-C, so it is checked code reaching the kernel only
/// through Fil-C's libc, which also tells the GC before blocking.
///
/// Every argument arrives as a pointer, so a real pointer (a futex word, a
/// timespec) keeps its capability. It returns the kernel's convention, -errno
/// on failure, because that is what the Zig code around the asm expects.
///
/// Fil-C's generic `syscall()` handles some numbers (gettid, futex) but rejects
/// others ("unsupported syscall: 230"), so those go to their libc function.
/// Measured 2026-09-30 by tools/p3/syscall-probe.c.
const syscall_helper_c =
    \\// Generated by zilc: raw system calls from Zig's std, routed through Fil-C's libc.
    \\#define _GNU_SOURCE
    \\#include <errno.h>
    \\#include <sys/syscall.h>
    \\#include <time.h>
    \\#include <unistd.h>
    \\
    \\long zilc_syscall(long n, void *a1, void *a2, void *a3, void *a4, void *a5, void *a6) {
    \\    long r;
    \\    switch (n) {
    \\    case SYS_clock_nanosleep: {
    \\        // Rejected by Fil-C's generic syscall(); libc's returns an errno value.
    \\        int e = clock_nanosleep((clockid_t)(long)a1, (int)(long)a2, a3, a4);
    \\        return e ? -e : 0;
    \\    }
    \\    case SYS_futex:
    \\        // Fil-C emulates futexes in user space; the word and timeout keep their capabilities.
    \\        r = syscall(SYS_futex, a1, (long)a2, (long)a3, a4, a5, (long)a6);
    \\        break;
    \\    default:
    \\        r = syscall(n, a1, a2, a3, a4, a5, a6);
    \\        break;
    \\    }
    \\    return r == -1 ? -errno : r;
    \\}
    \\
;

/// Zig's compiler-rt files implementing 128-bit float (`f128`) arithmetic (KI-9).
/// LLVM lowers f128 operations to calls into these, but compiler-rt is never
/// compiled through the pass, so under Fil-C nothing checked provides them. When
/// a program uses f128, zilc compiles these files through the same pipeline as
/// the program, so they are checked code too.
const f128_rt_files = [_][]const u8{
    "addtf3",     "subtf3",      "multf3",      "divtf3",      "cmptf2",      "getf2",
    "unordtf2",   "extendsftf2", "extenddftf2", "trunctfsf2",  "trunctfdf2",  "fixtfsi",
    "fixtfdi",    "fixtfti",     "fixunstfsi",  "fixunstfdi",  "fixunstfti",  "floatsitf",
    "floatditf",  "floattitf",   "floatunsitf", "floatunditf", "floatuntitf", "extendxftf2",
    "trunctfxf2", "round",
};

/// The only symbols those files may export. Everything else is made internal,
/// so that, for example, round.zig's `round` and `roundf` cannot displace Fil-C's
/// own libm functions for C code linked into the same program.
const f128_rt_exports = [_][]const u8{
    "__addtf3",    "__subtf3",     "__multf3",     "__divtf3",     "__cmptf2",     "__eqtf2",
    "__netf2",     "__lttf2",      "__letf2",      "__getf2",      "__gttf2",      "__unordtf2",
    "__extendsftf2", "__extenddftf2", "__trunctfsf2", "__trunctfdf2", "__fixtfsi",  "__fixtfdi",
    "__fixtfti",   "__fixunstfsi", "__fixunstfdi", "__fixunstfti", "__floatsitf",  "__floatditf",
    "__floattitf", "__floatunsitf", "__floatunditf", "__floatuntitf", "__extendxftf2",
    "__trunctfxf2", "roundq",
};

/// Zig's lib directory, from `zig env` (ZON: `.lib_dir = "…"`).
fn zigLibDir(gpa: std.mem.Allocator, zig: []const u8) ![]u8 {
    const res = try std.process.Child.run(.{ .allocator = gpa, .argv = &.{ zig, "env" } });
    defer gpa.free(res.stdout);
    defer gpa.free(res.stderr);
    const key = ".lib_dir = \"";
    const start = (std.mem.indexOf(u8, res.stdout, key) orelse return Error.ToolFailed) + key.len;
    const end = std.mem.indexOfScalarPos(u8, res.stdout, start, '"') orelse return Error.ToolFailed;
    // ZON escapes backslashes (Windows paths); Linux paths come through unchanged.
    return std.mem.replaceOwned(u8, gpa, res.stdout[start..end], "\\\\", "\\");
}

/// Does this Zig file look like a program (rather than a library of exports)?
///
/// Textual, deliberately: parsing Zig to answer it would be a compiler, and a
/// wrong guess is cheap to override with `--entry`.
fn declaresMain(gpa: std.mem.Allocator, path: []const u8) bool {
    const src = std.fs.cwd().readFileAlloc(gpa, path, 16 * 1024 * 1024) catch return false;
    defer gpa.free(src);
    return std.mem.indexOf(u8, src, "pub fn main(") != null;
}

/// What a given input file needs: Zig compiles it to IR first, or Fil-C takes it directly.
fn classify(path: []const u8) !enum { zig, native } {
    const ext = std.fs.path.extension(path);
    if (std.mem.eql(u8, ext, ".zig")) return .zig;
    inline for (.{ ".c", ".cc", ".cpp", ".cxx", ".o", ".a", ".s", ".ll" }) |known| {
        if (std.mem.eql(u8, ext, known)) return .native;
    }
    return Error.UnsupportedInput;
}

fn run(gpa: std.mem.Allocator, argv: []const []const u8, verbose: bool) !void {
    if (verbose) {
        for (argv, 0..) |a, i| std.debug.print("{s}{s}", .{ if (i == 0) "+ " else " ", a });
        std.debug.print("\n", .{});
    }
    var child = std.process.Child.init(argv, gpa);
    child.stdin_behavior = .Inherit;
    child.stdout_behavior = .Inherit;
    child.stderr_behavior = .Inherit;
    const term = child.spawnAndWait() catch |e| {
        std.debug.print("zilc: cannot run '{s}': {s}\n", .{ argv[0], @errorName(e) });
        return Error.ToolFailed;
    };
    switch (term) {
        .Exited => |code| if (code != 0) {
            std.debug.print("zilc: '{s}' exited with {d}\n", .{ argv[0], code });
            return Error.ToolFailed;
        },
        else => {
            std.debug.print("zilc: '{s}' terminated abnormally\n", .{argv[0]});
            return Error.ToolFailed;
        },
    }
}

/// Zig source → LLVM IR → Fil-C-dialect IR → object file. Returns the object path.
fn compileZig(
    gpa: std.mem.Allocator,
    opts: Options,
    tmp_path: []const u8,
    src: []const u8,
    /// Wrap this file in the generated entry shim, so it can own `main`.
    is_entry: bool,
    /// Set if this module's raw `syscall` asm was redirected to `zilc_syscall`,
    /// so the link needs the helper (KI-7).
    needs_syscall_helper: *bool,
    /// Set if this module uses 128-bit floats, so the link needs the f128
    /// compiler-rt helpers (KI-9).
    uses_f128: *bool,
    /// If set, every function definition not named here is made internal.
    keep_exports: ?[]const []const u8,
) ![]u8 {
    const stem = std.fs.path.stem(src);
    const ll_path = try std.fmt.allocPrint(gpa, "{s}/{s}.ll", .{ tmp_path, stem });
    defer gpa.free(ll_path);
    const filc_ll_path = try std.fmt.allocPrint(gpa, "{s}/{s}.filc.ll", .{ tmp_path, stem });
    defer gpa.free(filc_ll_path);
    const obj_path = try std.fmt.allocPrint(gpa, "{s}/{s}.o", .{ tmp_path, stem });
    errdefer gpa.free(obj_path);

    // 1. Stock Zig emits plain LLVM IR. `-fno-emit-bin`: we only want the IR.
    const emit_arg = try std.fmt.allocPrint(gpa, "-femit-llvm-ir={s}", .{ll_path});
    defer gpa.free(emit_arg);

    var zig_args: std.ArrayListUnmanaged([]const u8) = .{};
    defer zig_args.deinit(gpa);
    try zig_args.appendSlice(gpa, &.{
        opts.zig,  "build-obj",
        "-target", opts.target,
        "-O",      opts.optimize,
        "-fno-emit-bin", emit_arg,
        // Always: Fil-C always links its libc, and without -lc Zig's std reaches
        // the kernel through raw `syscall` asm in many more places (KI-7).
        "-lc",
    });
    // Every mode, not only Debug: ReleaseSafe emits the probe too for large frames
    // (std.debug's stack-trace code, std.fs path buffers), and it fails the link the
    // same way. Fil-C checks the stack at every function entry anyway (KI-8).
    try zig_args.append(gpa, "-fno-stack-check");

    var shim_path: ?[]u8 = null;
    defer if (shim_path) |p| gpa.free(p);

    if (is_entry) {
        // The shim is the ROOT and the user's file is a module, which is what
        // keeps `start.zig` out of the build entirely.
        const p = try std.fmt.allocPrint(gpa, "{s}/zilc_entry.zig", .{tmp_path});
        shim_path = p;
        try std.fs.cwd().writeFile(.{ .sub_path = p, .data = entry_shim });

        const root_arg = try std.fmt.allocPrint(gpa, "-Mroot={s}", .{p});
        defer gpa.free(root_arg);
        const user_arg = try std.fmt.allocPrint(gpa, "-Muser={s}", .{src});
        defer gpa.free(user_arg);
        try zig_args.appendSlice(gpa, &.{ "--dep", "user", root_arg, user_arg });
        try run(gpa, zig_args.items, opts.verbose);
    } else {
        try zig_args.append(gpa, src);
        try run(gpa, zig_args.items, opts.verbose);
    }

    // 2. The rewrite: two lines, and the whole reason this driver exists.
    const plain = try std.fs.cwd().readFileAlloc(gpa, ll_path, 512 * 1024 * 1024);
    defer gpa.free(plain);
    const dialect = ir.toFilCDialect(gpa, plain) catch |e| {
        std.debug.print("zilc: cannot rewrite IR for '{s}': {s}\n", .{ src, @errorName(e) });
        return Error.ToolFailed;
    };
    defer gpa.free(dialect);
    // 2b. Zig's raw `syscall` asm, which Fil-C refuses, goes through the checked libc (KI-7).
    const routed = try ir.rewriteSyscalls(gpa, dialect);
    defer gpa.free(routed.ir);
    if (routed.count > 0) {
        needs_syscall_helper.* = true;
        if (opts.verbose) std.debug.print("zilc: {s}: {d} raw syscall(s) routed through {s}\n", .{ src, routed.count, ir.syscall_helper });
    }
    if (std.mem.indexOf(u8, routed.ir, "fp128") != null) uses_f128.* = true;
    const final_ir = if (keep_exports) |keep| try ir.internalizeExcept(gpa, routed.ir, keep) else null;
    defer if (final_ir) |f| gpa.free(f);
    try std.fs.cwd().writeFile(.{ .sub_path = filc_ll_path, .data = final_ir orelse routed.ir });

    // 3. Fil-C's clang runs the pass and emits the object.
    //
    // `-Wno-override-module`: Zig names the triple `…-linux-musl` while Fil-C's
    // driver is `…-linux-gnu`, so clang warns that it is overriding ours. It is
    // expected, not a mismatch to fix — Fil-C's libc *is* musl whatever its
    // triple says, which is why the musl target is the one that links (KI-6).
    const filc_opt: []const u8 = if (isDebug(opts.optimize)) "-O0" else "-O1";
    try run(gpa, &.{
        opts.filc, filc_opt, "-g", "-Wno-override-module", "-c", "-o", obj_path, filc_ll_path,
    }, opts.verbose);
    return obj_path;
}

pub fn build(gpa: std.mem.Allocator, opts: Options) !void {
    if (opts.inputs.len == 0) return Error.NoInputs;
    if (opts.runtime == .zig) {
        std.debug.print(
            \\zilc: --runtime zig is reserved: the Zig runtime is not ready for testing
            \\  yet (cmem/roadmap.md P3). Use --runtime filc, the default.
            \\
        , .{});
        return Error.RuntimeNotReady;
    }

    // Temps live beside the output so a failed build leaves them inspectable
    // with --keep-temps, which is how KI-4/KI-5 were diagnosed in the first place.
    const tmp_path = try std.fmt.allocPrint(gpa, "{s}.zilc-tmp", .{opts.output});
    defer gpa.free(tmp_path);
    try std.fs.cwd().makePath(tmp_path);
    defer if (!opts.keep_temps) {
        std.fs.cwd().deleteTree(tmp_path) catch {};
    } else std.debug.print("zilc: kept intermediates in {s}/\n", .{tmp_path});

    var link_args: std.ArrayListUnmanaged([]const u8) = .{};
    defer link_args.deinit(gpa);
    var owned: std.ArrayListUnmanaged([]u8) = .{};
    defer {
        for (owned.items) |p| gpa.free(p);
        owned.deinit(gpa);
    }

    try link_args.appendSlice(gpa, &.{ opts.filc, "-O1", "-g" });

    // Which input owns `main`? In `.auto`, a lone Zig file declaring `pub fn main`
    // with no C/C++ beside it gets the generated entry shim; anything else
    // assumes C owns `main`, which is the shape the interop example uses.
    var entry_index: ?usize = null;
    if (opts.entry != .c and opts.emit == .exe) {
        var has_native = false;
        for (opts.inputs) |input| {
            if ((try classify(input)) == .native) has_native = true;
        }
        for (opts.inputs, 0..) |input, i| {
            if ((try classify(input)) != .zig) continue;
            const wants = switch (opts.entry) {
                .zig => true,
                .auto => !has_native and declaresMain(gpa, input),
                .c => false,
            };
            if (wants) {
                entry_index = i;
                break;
            }
        }
        if (opts.entry == .zig and entry_index == null) {
            std.debug.print("zilc: --entry zig, but no .zig input was given\n", .{});
            return Error.NoInputs;
        }
    }

    var needs_syscall_helper = false;
    var uses_f128 = false;
    for (opts.inputs, 0..) |input, i| {
        switch (try classify(input)) {
            .zig => {
                const obj = try compileZig(gpa, opts, tmp_path, input, entry_index == i, &needs_syscall_helper, &uses_f128, null);
                try owned.append(gpa, obj);
                try link_args.append(gpa, obj);
            },
            // C/C++/objects go to Fil-C untouched: it is already their compiler.
            .native => try link_args.append(gpa, input),
        }
    }

    // 128-bit floats: the compiler-rt helpers, compiled through the pass (KI-9).
    if (uses_f128) {
        const lib_dir = try zigLibDir(gpa, opts.zig);
        defer gpa.free(lib_dir);
        // Their own subdirectory, so a user file named like one (round.zig) cannot collide.
        const rt_tmp = try std.fmt.allocPrint(gpa, "{s}/compiler_rt", .{tmp_path});
        defer gpa.free(rt_tmp);
        try std.fs.cwd().makePath(rt_tmp);
        if (opts.verbose) std.debug.print("zilc: f128 in use: compiling {d} compiler-rt files through Fil-C\n", .{f128_rt_files.len});
        var unused = false;
        for (f128_rt_files) |name| {
            const src = try std.fmt.allocPrint(gpa, "{s}/compiler_rt/{s}.zig", .{ lib_dir, name });
            defer gpa.free(src);
            const obj = try compileZig(gpa, opts, rt_tmp, src, false, &needs_syscall_helper, &unused, &f128_rt_exports);
            try owned.append(gpa, obj);
            try link_args.append(gpa, obj);
        }
    }

    // One helper object for every module whose raw syscalls were redirected (KI-7).
    var helper_obj: ?[]u8 = null;
    defer if (helper_obj) |p| gpa.free(p);
    if (needs_syscall_helper) {
        const c_path = try std.fmt.allocPrint(gpa, "{s}/{s}.c", .{ tmp_path, ir.syscall_helper });
        defer gpa.free(c_path);
        const o_path = try std.fmt.allocPrint(gpa, "{s}/{s}.o", .{ tmp_path, ir.syscall_helper });
        helper_obj = o_path;
        try std.fs.cwd().writeFile(.{ .sub_path = c_path, .data = syscall_helper_c });
        try run(gpa, &.{ opts.filc, "-O1", "-g", "-c", "-o", o_path, c_path }, opts.verbose);
        try link_args.append(gpa, o_path);
    }

    if (opts.emit == .obj) {
        // Object-only: the .o files are the product, so copy them out.
        for (owned.items) |obj| {
            try std.fs.cwd().copyFile(obj, std.fs.cwd(), opts.output, .{});
        }
        if (helper_obj) |o| {
            // Without it the final link fails on `zilc_syscall`; hand it over beside the output.
            const dest = try std.fmt.allocPrint(gpa, "{s}.{s}.o", .{ opts.output, ir.syscall_helper });
            defer gpa.free(dest);
            try std.fs.cwd().copyFile(o, std.fs.cwd(), dest, .{});
            std.debug.print("zilc: note: also link {s} (raw syscalls routed through Fil-C's libc)\n", .{dest});
        }
        return;
    }

    try link_args.appendSlice(gpa, &.{ "-o", opts.output });
    try run(gpa, link_args.items, opts.verbose);
}

test "--runtime zig is refused before anything runs" {
    // No tool is invoked and no temp dir is made: the refusal comes first,
    // so the paths here never need to exist.
    try std.testing.expectError(Error.RuntimeNotReady, build(std.testing.allocator, .{
        .inputs = &.{"never-read.zig"},
        .output = "never-written",
        .runtime = .zig,
        .zig = "zig",
        .filc = "clang",
    }));
}
